import { Link, useForm } from '@inertiajs/react';
import FormField from '../../Components/FormField';
import AuthLayout from '../../Layouts/AuthLayout';

type Props = { status?: string; oauthError?: string; oauthProviders: Array<'google' | 'facebook'> };

export default function Login({ status, oauthError, oauthProviders }: Props) {
    const form = useForm({ email: '', password: '', remember: false });
    return <AuthLayout title="Đăng nhập" description="Quản lý đơn hàng, địa chỉ giao hàng và sản phẩm yêu thích.">{status && <p className="mb-4 text-sm text-emerald-700">{status}</p>}{oauthError && <p role="alert" className="mb-4 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{oauthError}</p>}{oauthProviders.length > 0 && <><div className="grid gap-3 sm:grid-cols-2">{oauthProviders.includes('google') && <a href="/dang-nhap/google" className="grid h-11 place-items-center border border-[#cdd9e6] bg-white text-sm font-bold text-[#25496d] hover:border-[#0b4fa4]">Tiếp tục với Google</a>}{oauthProviders.includes('facebook') && <a href="/dang-nhap/facebook" className="grid h-11 place-items-center bg-[#1877f2] text-sm font-bold text-white hover:bg-[#1264cf]">Tiếp tục với Facebook</a>}</div><div className="my-5 flex items-center gap-3 text-xs uppercase tracking-[.16em] text-[#8a9bad]"><span className="h-px flex-1 bg-[#dce5ef]"/><span>hoặc email</span><span className="h-px flex-1 bg-[#dce5ef]"/></div></>}<form onSubmit={e => { e.preventDefault(); form.post('/dang-nhap'); }} className="space-y-4"><FormField label="Email" type="email" autoComplete="email" value={form.data.email} onChange={e => form.setData('email', e.target.value)} error={form.errors.email}/><FormField label="Mật khẩu" type="password" autoComplete="current-password" value={form.data.password} onChange={e => form.setData('password', e.target.value)} error={form.errors.password}/><label className="flex items-center gap-2 text-sm text-[#607b98]"><input type="checkbox" checked={form.data.remember} onChange={e => form.setData('remember', e.target.checked)}/> Ghi nhớ đăng nhập</label><button disabled={form.processing} className="h-11 w-full bg-[#0b4fa4] font-bold text-white disabled:opacity-60">Đăng nhập</button></form><div className="mt-5 flex justify-between text-sm text-[#0b4fa4]"><Link href="/quen-mat-khau">Quên mật khẩu?</Link><Link href="/dang-ky">Tạo tài khoản</Link></div></AuthLayout>;
}
