import { Link, useForm, usePage } from '@inertiajs/react';
import { ChevronRight, Eye, Minus, Plus, ShieldCheck, Star } from 'lucide-react';
import { useState } from 'react';
import SeoHead from '../../Components/SeoHead';
import { AddToCartButton, WishlistButton } from '../../Components/CommerceActions';
import { CompareButton } from '../../Components/Compare';
import StoreLayout from '../../Layouts/StoreLayout';

type ProductImage = {url:string;alt_text?:string|null;is_primary?:boolean;variants?:Record<string,string>};
type Product = { id:number; name:string; slug:string; sku:string; short_description:string; price:string; original_price?:string|null; sale_price?:string|null; stock:number; is_available:boolean; badge?:string; btu?:number|null; room_size?:string|null; inverter?:boolean|null; brand:{name:string;slug:string}; category:{name:string;slug:string}; images:ProductImage[]; specifications:{name:string;value:string}[]; url:string; image?:ProductImage|null };
const money=(value:string|number)=>Number(value).toLocaleString('vi-VN')+'₫';

type Review = { id:number; rating:number; title?:string|null; content?:string|null; reviewer_name?:string|null; verified_purchase:boolean; approved_at?:string|null };
export default function ProductShow({product,seo,breadcrumbs,jsonLd,reviews,reviewSummary,myReview}:{product:Product;seo:any;breadcrumbs:any[];jsonLd:any;reviews:Review[];reviewSummary:{count:number;average:number|null};myReview?:{status:string}|null}){
 const [image,setImage]=useState(product.images[0]?.url); const [qty,setQty]=useState(1); const [tab,setTab]=useState('specs'); const [installation,setInstallation]=useState(false); const price=product.sale_price||product.price; const activeImage=product.images.find(item=>item.url===image); const srcSet=activeImage?.variants?Object.entries(activeImage.variants).map(([width,url])=>`${url} ${width}w`).join(', '):undefined;
 const user=(usePage().props as any).auth?.user; const reviewForm=useForm({rating:5,title:'',content:''});
 return <StoreLayout><SeoHead seo={seo} jsonLd={jsonLd}/><main className="container-store py-7 fade-up">
  <nav aria-label="Breadcrumb" className="mb-5 flex items-center gap-2 overflow-hidden text-xs text-[#8293a8]">{breadcrumbs.map((b,i)=><span key={b.url} className="flex min-w-0 items-center gap-2">{i>0&&<ChevronRight size={14}/>}<Link href={b.url} className={i===breadcrumbs.length-1?'line-clamp-1 font-bold text-[#214665]':'hover:text-[#0b4fa4]'}>{b.name}</Link></span>)}</nav>
  <div className="grid gap-9 lg:grid-cols-2"><section className="grid gap-3 sm:grid-cols-[76px_1fr]"><div className="order-2 flex gap-2 overflow-x-auto sm:order-1 sm:flex-col">{product.images.map((g,i)=><button key={g.url} onClick={()=>setImage(g.url)} className={`h-16 w-16 shrink-0 overflow-hidden border-2 bg-[#f4f8fc] ${image===g.url?'border-[#0b4fa4]':'border-transparent'}`}><img src={g.url} alt={g.alt_text||`${product.name} - ảnh ${i+1}`} loading="lazy" className="h-full w-full object-cover mix-blend-multiply"/></button>)}</div><div className="relative order-1 flex aspect-square items-center justify-center overflow-hidden bg-[#f4f8fc] sm:order-2"><img src={image} srcSet={srcSet} sizes="(min-width: 1024px) 50vw, 100vw" alt={product.name} className="h-full w-full object-cover mix-blend-multiply"/><span className="absolute bottom-3 left-3 flex items-center gap-1 bg-white/85 px-2 py-1 text-[10px] text-[#607991]"><Eye size={13}/> Xem ảnh sản phẩm</span></div></section>
  <section><div className="text-xs font-bold uppercase tracking-[.2em] text-[#8294a9]">{product.brand.name} · {product.category.name}</div><h1 className="mt-2 font-display text-2xl font-bold leading-tight text-[#14385f] sm:text-3xl">{product.name}</h1><p className="mt-3 text-sm leading-6 text-[#5e7792]">{product.short_description}</p><div className="mt-6 border-y border-[#e1e8f0] py-5"><div className="flex items-end gap-3"><span className="text-3xl font-extrabold text-[#d44b2e]">{money(price)}</span>{product.original_price&&<span className="text-sm text-[#94a2b0] line-through">{money(product.original_price)}</span>}</div><p className="mt-2 text-xs text-[#71869d]">Giá đã gồm VAT · SKU: {product.sku}</p></div>
  <div className="mt-5 space-y-1"><b className="text-sm text-[#214665]">Điểm nổi bật</b>{product.specifications.slice(0,3).map(s=><div key={s.name} className="flex justify-between border-b border-dashed border-[#e1e8f0] py-3 text-sm"><span className="text-[#71869d]">{s.name}</span><b className="text-[#315575]">{s.value}</b></div>)}</div>
  <div className="mt-5 flex items-center gap-3"><span className="text-sm font-semibold text-[#315575]">Số lượng</span><div className="flex border border-[#d5e1ec]"><button className="grid h-9 w-9 place-items-center" onClick={()=>setQty(Math.max(1,qty-1))}><Minus size={14}/></button><span className="grid h-9 w-9 place-items-center text-sm font-bold">{qty}</span><button className="grid h-9 w-9 place-items-center" onClick={()=>setQty(Math.min(product.stock,qty+1))}><Plus size={14}/></button></div><span className="text-xs text-[#168265]">{product.is_available?`Còn ${product.stock} sản phẩm`:'Tạm hết hàng'}</span></div>
  <label className="mt-4 flex items-center gap-2 text-sm text-[#315575]"><input type="checkbox" checked={installation} onChange={e=>setInstallation(e.target.checked)}/> Yêu cầu dịch vụ lắp đặt (phí được backend báo theo sản phẩm)</label><div className="mt-5 flex gap-2"><AddToCartButton productId={product.id} quantity={qty} installationRequired={installation} className="flex flex-1 items-center justify-center gap-2 border-2 border-[#0b4fa4] py-3 text-sm font-bold text-[#0b4fa4]">Thêm vào giỏ</AddToCartButton><AddToCartButton productId={product.id} quantity={qty} installationRequired={installation} redirectTo="/thanh-toan" className="flex flex-1 items-center justify-center bg-[#e65a37] py-3 text-sm font-bold text-white">Mua ngay</AddToCartButton></div><div className="mt-3 flex gap-2"><CompareButton product={product} className="flex flex-1 items-center justify-center gap-2 border border-[#d5e1ec] py-2 text-xs font-bold text-[#5e7792] disabled:opacity-40"/><WishlistButton productId={product.id} className="flex items-center gap-2 border border-[#d5e1ec] px-4 text-xs font-bold text-[#5e7792]"/></div></section></div>
  <section className="mt-12 border-y border-[#dce5ef]"><div className="flex gap-5 overflow-x-auto">{[['specs','Thông số kỹ thuật'],['delivery','Giao hàng & lắp đặt'],['warranty','Bảo hành']].map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`shrink-0 border-b-2 py-4 text-sm font-bold ${tab===key?'border-[#0b4fa4] text-[#0b4fa4]':'border-transparent text-[#71869d]'}`}>{label}</button>)}</div><div className="grid gap-8 py-7 md:grid-cols-2"><div>{tab==='specs'?product.specifications.map(s=><div key={s.name} className="flex border-b border-[#edf1f5] py-3 text-sm"><span className="w-1/2 text-[#71869d]">{s.name}</span><b className="text-[#315575]">{s.value}</b></div>):<p className="text-sm leading-7 text-[#5e7792]">{tab==='delivery'?'Miễn phí giao hàng trong bán kính 20 km. Dịch vụ lắp đặt được xác nhận trước khi kỹ thuật viên đến.':'Bảo hành chính hãng theo thời hạn công bố của sản phẩm.'}</p>}</div><div className="bg-[#f4f8fc] p-5"><div className="flex items-center gap-3"><ShieldCheck className="text-[#168265]"/><div><b className="text-sm text-[#214665]">Mua hàng an tâm</b><p className="mt-1 text-xs leading-5 text-[#71869d]">Hàng chính hãng, kiểm tra trước khi nhận. Hỗ trợ đổi trả minh bạch.</p></div></div></div></div></section>
  <section className="py-10"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-display text-2xl font-bold text-[#14385f]">Đánh giá sản phẩm</h2><p className="mt-1 text-sm text-[#71869d]">{reviewSummary.count>0?`${reviewSummary.average}/5 từ ${reviewSummary.count} đánh giá đã duyệt`:'Chưa có đánh giá đã duyệt'}</p></div></div><div className="mt-6 grid gap-7 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{reviews.length===0?<p className="border border-dashed border-[#cbd8e5] p-6 text-sm text-[#71869d]">Hãy là người đầu tiên chia sẻ trải nghiệm thực tế.</p>:reviews.map(review=><article key={review.id} className="border border-[#dce5ef] p-4"><div className="flex items-center gap-1 text-[#f2ad16]">{Array.from({length:5},(_,i)=><Star key={i} size={15} fill={i<review.rating?'currentColor':'none'}/>)}</div><h3 className="mt-2 font-bold text-[#214665]">{review.title||'Đánh giá sản phẩm'}</h3><p className="mt-2 text-sm leading-6 text-[#607b98]">{review.content}</p><p className="mt-3 text-xs text-[#8294a9]">{review.reviewer_name}{review.verified_purchase&&<span className="ml-2 font-bold text-[#168265]">Đã mua hàng</span>}</p></article>)}</div><aside className="h-fit bg-[#f4f8fc] p-5">{!user?<><b className="text-[#214665]">Bạn đã dùng sản phẩm?</b><p className="mt-2 text-sm text-[#71869d]">Đăng nhập để gửi đánh giá.</p><Link href="/dang-nhap" className="mt-4 inline-flex bg-[#0b4fa4] px-4 py-2 text-sm font-bold text-white">Đăng nhập</Link></>:myReview?<><b className="text-[#214665]">Đánh giá của bạn</b><p className="mt-2 text-sm text-[#71869d]">Trạng thái: {myReview.status}. Bạn có thể gửi lại để cập nhật và chờ duyệt.</p></>:<form onSubmit={e=>{e.preventDefault();reviewForm.post(`/san-pham/${product.slug}/danh-gia`,{preserveScroll:true});}}><b className="text-[#214665]">Viết đánh giá</b><label className="mt-4 block text-xs font-bold text-[#315575]">Số sao<select value={reviewForm.data.rating} onChange={e=>reviewForm.setData('rating',Number(e.target.value))} className="mt-1 h-10 w-full border border-[#cbd8e5] bg-white px-3">{[5,4,3,2,1].map(v=><option key={v} value={v}>{v} sao</option>)}</select></label><input value={reviewForm.data.title} onChange={e=>reviewForm.setData('title',e.target.value)} placeholder="Tiêu đề (không bắt buộc)" className="mt-3 h-10 w-full border border-[#cbd8e5] px-3 text-sm"/><textarea value={reviewForm.data.content} onChange={e=>reviewForm.setData('content',e.target.value)} placeholder="Chia sẻ trải nghiệm tối thiểu 20 ký tự" className="mt-3 min-h-28 w-full border border-[#cbd8e5] p-3 text-sm"/>{Object.values(reviewForm.errors).map(error=><p key={error} className="mt-1 text-xs text-[#c84b25]">{error}</p>)}<button disabled={reviewForm.processing} className="mt-3 bg-[#0b4fa4] px-4 py-2 text-sm font-bold text-white disabled:opacity-50">Gửi đánh giá</button></form>}</aside></div></section>
 </main></StoreLayout>;
}
