import { Link, usePage } from '@inertiajs/react';
import { Award, ChevronRight, Headphones, ShieldCheck, Truck } from 'lucide-react';
import CatalogProductCard, { type CatalogProduct } from '../Components/CatalogProductCard';
import SeoHead from '../Components/SeoHead';
import StoreLayout from '../Layouts/StoreLayout';

type Category = { name: string; slug: string; product_count: number; url: string };
type Brand = { name: string; slug: string; logo?: string; product_count: number; url: string };
type Article = { title: string; excerpt?: string; featured_image?: string; published_at?: string; url: string };
type Props = { site: { name: string; url: string }; heroProduct?: CatalogProduct; categories: Category[]; saleProducts: CatalogProduct[]; bestSellers: CatalogProduct[]; categorySections: { category: { name: string; url: string }; products: CatalogProduct[] }[]; brands: Brand[]; articles: Article[] };
const icons: Record<string, string> = { 'dieu-hoa': '❄', 'tu-lanh': '▣', 'may-giat': '◉', tivi: '▰', 'do-gia-dung': '♨', 'may-nuoc-nong': '♨', 'may-hut-bui': '◌', quat: '✥' };

function ProductSection({ title, products, href, accent = false }: { title: string; products: CatalogProduct[]; href?: string; accent?: boolean }) {
    if (!products.length) return null;
    return <section className={accent ? 'bg-[#0b4fa4] py-10' : 'py-10'}><div className="container-store"><div className="mb-5 flex items-end justify-between"><h2 className={`font-display text-2xl font-extrabold sm:text-3xl ${accent ? 'text-white' : 'text-[#14385f]'}`}>{title}</h2>{href && <Link href={href} className={`flex items-center gap-1 text-sm font-bold ${accent ? 'text-[#ffd45b]' : 'text-[#0b4fa4]'}`}>Xem tất cả <ChevronRight size={16}/></Link>}</div><div className="grid grid-cols-2 gap-2 sm:gap-4 lg:grid-cols-5">{products.map(product => <CatalogProductCard key={product.id} product={product}/>)}</div></div></section>;
}

export default function Home() {
    const { site, heroProduct, categories, saleProducts, bestSellers, categorySections, brands, articles } = usePage<Props>().props;
    const hero = heroProduct;
    const seo = { title: 'Điện Máy 365 | Điện máy chính hãng, giao lắp tận tâm', description: 'Mua điều hòa, tủ lạnh, máy giặt, tivi và thiết bị gia dụng chính hãng. Giá tốt, giao nhanh, hỗ trợ lắp đặt tận nơi.', canonical: site.url, ogType: 'website' as const };
    return <StoreLayout><SeoHead seo={seo} jsonLd={{ organization: { '@context': 'https://schema.org', '@type': 'Organization', name: site.name, url: site.url, telephone: '1800 6865' } }}/><main>
        <section className="overflow-hidden bg-gradient-to-r from-[#eaf4ff] via-white to-[#fff3d3]"><div className="container-store grid min-h-[380px] items-center gap-8 py-10 md:grid-cols-2"><div><p className="text-xs font-extrabold uppercase tracking-[.22em] text-[#e05a31]">Mùa nóng, nhà mát</p><h1 className="mt-3 font-display text-4xl font-black leading-tight text-[#103963] sm:text-5xl">Mát nhà. Nhẹ ví.<br/>Sống vui.</h1><p className="mt-4 max-w-xl text-[#59738e]">Điều hòa inverter chính hãng, tư vấn đúng công suất và hỗ trợ giao lắp tận nơi.</p><Link href="/dieu-hoa" className="mt-7 inline-flex items-center gap-2 bg-[#0b4fa4] px-6 py-3 font-bold text-white">Khám phá ngay <ChevronRight size={18}/></Link></div>{hero?.image && <img src={hero.image.url} alt={hero.image.alt_text || hero.name} width="720" height="480" fetchPriority="high" className="mx-auto h-72 w-full object-contain mix-blend-multiply md:h-80"/>}</div></section>
        <section className="border-y border-[#dce5ef] bg-white"><div className="container-store grid grid-cols-2 divide-x divide-y divide-[#e3eaf1] md:grid-cols-4 md:divide-y-0">{[[Truck,'Giao hàng nhanh','Miễn phí theo chính sách'],[Award,'Lắp đặt chuyên nghiệp','Kỹ thuật viên tận tâm'],[ShieldCheck,'Bảo hành chính hãng','Thông tin minh bạch'],[Headphones,'Hỗ trợ 1800 6865','Tư vấn mỗi ngày']].map(([Icon,title,text]) => { const I = Icon as typeof Truck; return <div key={title as string} className="flex gap-3 p-4"><I className="shrink-0 text-[#0b4fa4]"/><div><b className="text-sm text-[#173b68]">{title as string}</b><p className="text-xs text-[#7890a7]">{text as string}</p></div></div> })}</div></section>
        <section className="container-store py-10"><h2 className="font-display text-2xl font-extrabold text-[#14385f]">Danh mục nổi bật</h2><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{categories.map(category => <Link key={category.slug} href={category.url} className="group border border-[#dce5ef] bg-white p-4 text-center transition hover:border-[#0b4fa4] hover:shadow-md"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[#edf5ff] text-2xl text-[#0b4fa4]">{icons[category.slug] || '◆'}</span><h2 className="mt-3 text-sm font-bold text-[#244766]">{category.name}</h2><p className="mt-1 text-[11px] text-[#8093a6]">{category.product_count} sản phẩm</p></Link>)}</div></section>
        <ProductSection title="Giá sốc hôm nay" products={saleProducts} href="/tim-kiem?sort=sale" accent/>
        <ProductSection title="Sản phẩm bán chạy" products={bestSellers} href="/tim-kiem"/>
        {categorySections.map(section => <ProductSection key={section.category.url} title={section.category.name} products={section.products} href={section.category.url}/>) }
        <section className="bg-[#f2f6fa] py-10"><div className="container-store"><h2 className="font-display text-2xl font-extrabold text-[#14385f]">Thương hiệu nổi bật</h2><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{brands.map(brand => <Link key={brand.slug} href={brand.url} className="flex min-h-20 flex-col items-center justify-center border border-[#dce5ef] bg-white p-3 text-center font-display text-lg font-black text-[#234d75] hover:border-[#0b4fa4]">{brand.name}<small className="mt-1 font-sans text-[10px] font-normal text-[#8294a7]">{brand.product_count} sản phẩm</small></Link>)}</div></div></section>
        {articles.length > 0 && <section className="container-store py-10"><div className="flex items-end justify-between"><h2 className="font-display text-2xl font-extrabold text-[#14385f]">Kinh nghiệm hay</h2><Link href="/tin-tuc" className="text-sm font-bold text-[#0b4fa4]">Xem tất cả</Link></div><div className="mt-5 grid gap-5 md:grid-cols-3">{articles.map(article => <article key={article.url} className="border border-[#dce5ef] bg-white">{article.featured_image && <Link href={article.url}><img src={article.featured_image} alt={article.title} loading="lazy" width="640" height="360" className="aspect-video w-full object-cover"/></Link>}<div className="p-4"><time className="text-xs text-[#8194a7]">{article.published_at}</time><h2 className="mt-2 text-lg font-extrabold leading-snug text-[#173b68]"><Link href={article.url}>{article.title}</Link></h2><p className="mt-2 line-clamp-2 text-sm text-[#647d94]">{article.excerpt}</p></div></article>)}</div></section>}
    </main></StoreLayout>;
}
